source "https://rubygems.org"
gem 'mail'
gem 'smarter_csv'
gem 'sidekiq'
gem 'devise'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'responders'
gem 'devise-jwt'
gem 'razorpay'
gem 'smarter_csv'
gem 'phonelib'
gem 'sassc-rails'
gem 'sprockets-rails'
gem "rails", "~> 8.0.2"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem 'pry'
gem 'rack-cors', :require => 'rack/cors'
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "bootsnap", require: false
gem "kamal", require: false
gem "thruster", require: false
group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
